# Generated by Django 5.2.6 on 2025-09-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Title (Uzbek)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Title (Russian)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('description_uz', models.TextField(verbose_name='Description (Uzbek)')),
                ('description_ru', models.TextField(verbose_name='Description (Russian)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('image', models.ImageField(upload_to='courses/', verbose_name='Image')),
                ('duration', models.CharField(max_length=100, verbose_name='Duration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
