# Generated by Django 5.2.6 on 2025-09-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_contactmessage_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='infoblock',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='infoblock',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='bio',
            new_name='bio_en',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='course',
            name='description_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='title_ru',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='title_uz',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infoblock',
            name='description_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infoblock',
            name='description_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infoblock',
            name='title_ru',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infoblock',
            name='title_uz',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='description_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='description_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='title_ru',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='title_uz',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='bio_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='name_ru',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='name_uz',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
