# Generated by Django 5.2.6 on 2025-09-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='footer/')),
                ('link_facebook', models.URLField(blank=True, null=True)),
                ('link_instagram', models.URLField(blank=True, null=True)),
                ('link_telegram', models.URLField(blank=True, null=True)),
                ('link_youtube', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
